name: Run Tests
on: [workflow_dispatch, pull_request]

jobs:
  test:
    name: "Test library"
    runs-on: ubuntu-22.04

    steps:
      - name: "Check out PR branch"
        uses: actions/checkout@v2

      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: "Run tests"
        run: ./gradlew test --console=plain

      - name: "Upload test reports"
        uses: actions/upload-artifact@v2
        if: failure() # This step will only run if a previous steps failed
        with:
          name: "test-reports"
          path: lib/build/reports/tests/test/
